/**
 * cp-daemon's backend port (cp-txbb): how this machine runs cp-daemon, and the only module that names
 * `systemctl`, `loginctl` or `journalctl` (tests/structure.test.ts ratchets it).
 *
 *   systemd    a thin `cp-daemon.service` runs `cp-daemon run` in the foreground (`renderDaemonUnit`);
 *              linger keeps it up without a login session
 *   detached   no user manager (a Coder VM): `cp-daemon start` setsid-spawns `run`; after a reboot the
 *              printed reboot command (or the opt-in `--crontab` @reboot line) starts it again
 *
 * `migrateLegacy` (M1, docs/service.md §Migration) moves a home off the six legacy units
 * (`cp-parent`/`cp-view` + the health and update timers) without touching the parent host or its
 * workers; `activate`/`deactivate` are cp-install's start and uninstall; `daemonFindings` and
 * `viewerExpected` feed /doctor (`status.ts`). Imports only `node:*` and `./daemon-*.ts`: daemon.ts loads it
 * into the outer process (`OUTER_SOURCES`).
 */
import { existsSync, readFileSync } from "node:fs";
import { userInfo } from "node:os";
import { join } from "node:path";
import {
	type Backend,
	type DaemonConfig,
	type DaemonPaths,
	daemonPaths,
	type DaemonState,
	type LockRecord,
	OUTER_ARGV,
	outerHash,
	pidAlive,
	psArgs,
	readDaemonConfig,
	readJson,
	rebootCommand,
	type RuntimeRecord,
	sameProcess,
} from "./daemon-files.ts";

export const DAEMON_UNIT = "cp-daemon.service";
/** What cp-install wrote before cp-daemon (units.ts renders them; tests/daemon-backend.test.ts pins the names). */
export const LEGACY_UNITS = ["cp-parent.service", "cp-view.service", "cp-health.service", "cp-health.timer", "cp-update.service", "cp-update.timer"] as const;
const [PARENT, VIEW, , HEALTH_TIMER, UPDATE, UPDATE_TIMER] = LEGACY_UNITS;
/** The legacy units install enabled; the oneshots ran from their timers. */
const LEGACY_ENABLED = [PARENT, VIEW, HEALTH_TIMER, UPDATE_TIMER];
const GENERATED = "Generated by cp-install";
export const READY_WAIT_MS = 60_000;

export interface RunResult { status: number; stdout: string; stderr: string }
export type Run = (command: string, args: readonly string[]) => RunResult;
type Step = (status: "ok" | "changed" | "skip" | "fail", name: string, detail: string) => void;

export function detectBackend(run: Run): { backend: Backend; detail: string } {
	const state = run("systemctl", ["--user", "is-system-running"]).stdout.trim();
	if (state === "running" || state === "degraded") return { backend: "systemd", detail: `systemctl --user is ${state}: cp-daemon runs as ${DAEMON_UNIT}` };
	return { backend: "detached", detail: `no systemd --user (${state || "unavailable"}): cp-daemon runs detached; after a reboot run the reboot command it prints` };
}

/** The CLI's start/stop/restart on the systemd backend: the unit is the process manager. */
export function systemdVerb(verb: "start" | "stop" | "restart", run: Run): { code: number; text: string } {
	const result = run("systemctl", ["--user", verb, DAEMON_UNIT]);
	return result.status === 0
		? { code: 0, text: `cp-daemon: systemctl --user ${verb} ${DAEMON_UNIT}: ok${verb === "stop" ? " (the parent host and workers keep running)" : ""}` }
		: { code: 1, text: `cp-daemon ${verb}: systemctl --user ${verb} ${DAEMON_UNIT} failed: ${result.stderr.trim() || `exit ${result.status}`}; journalctl --user -u ${DAEMON_UNIT} -n 20` };
}

/** How to start a stopped daemon, also after a reboot. */
export function startCommand(config: Pick<DaemonConfig, "backend" | "node" | "app" | "home">): string {
	return config.backend === "systemd" ? `systemctl --user start ${DAEMON_UNIT}` : rebootCommand(config);
}

// ---------------------------------------------------------------------------
// cp-install's half
// ---------------------------------------------------------------------------

/** What cp-install hands the backend; `InstallPorts` satisfies it. */
export interface BackendPorts {
	run(command: string, args: readonly string[], cwd?: string): RunResult;
	read(path: string): string | undefined;
	write(path: string, text: string, mode: number): void;
	exists(path: string): boolean;
	remove(path: string): void;
	sleep(ms: number): Promise<void>;
	env: NodeJS.ProcessEnv;
}

export interface BackendContext {
	ports: BackendPorts;
	/** What this install writes to `data/daemon.json`. */
	config: DaemonConfig;
	unitDir: string;
	dry: boolean;
	force: boolean;
	noStart: boolean;
	crontab: boolean;
	/** This run replaced the thin unit or `data/daemon.json` (a running daemon restarts onto them). */
	changed: boolean;
	step: Step;
	/** cp-rrye: more unit files M1 removes beside the legacy ones, only at its success (S8) and only when generated; never stopped. */
	retire?: readonly string[];
}

const unitFile = (ctx: Pick<BackendContext, "unitDir">, name: string) => join(ctx.unitDir, name);
const systemctl = (ctx: BackendContext, ...args: string[]) => ctx.ports.run("systemctl", ["--user", ...args]);
const failed = (result: RunResult, line: string) => (result.status === 0 ? undefined : `${line} failed: ${result.stderr.trim() || `exit ${result.status}`}`);
/** `cp-daemon <verb>` from the checkout being installed. */
const daemonCli = (ctx: BackendContext, verb: string) => ctx.ports.run(ctx.config.node, [`${ctx.config.app}/src/service/daemon.ts`, verb, "--home", ctx.config.home], ctx.config.home);

/** The legacy generated unit files present in the unit dir. */
export function legacyPresent(ports: Pick<BackendPorts, "exists">, unitDir: string): string[] {
	return LEGACY_UNITS.filter((name) => ports.exists(join(unitDir, name)));
}

function parse<T>(text: string | undefined): T | undefined {
	try {
		return text === undefined ? undefined : (JSON.parse(text) as T);
	} catch {
		return undefined;
	}
}

/** Why the daemon is not ready yet (the unit active on systemd, the inner ready, parent and viewer running); undefined when it is. */
function notReady(ctx: BackendContext, paths: DaemonPaths): string | undefined {
	if (ctx.config.backend === "systemd") {
		const active = systemctl(ctx, "is-active", DAEMON_UNIT).stdout.trim() || "unknown";
		if (active !== "active") return `${DAEMON_UNIT} is ${active}`;
	}
	const state = parse<DaemonState>(ctx.ports.read(paths.state));
	if (!state?.inner) return `no ${paths.state} yet`;
	if (state.inner.state !== "ready") return `its runtime is ${state.inner.state}${state.inner.detail ? ` (${state.inner.detail})` : ""}`;
	const units = parse<RuntimeRecord>(ctx.ports.read(paths.runtime))?.units;
	for (const role of ["parent", "viewer"] as const) {
		const unit = units?.[role];
		if (unit?.state !== "running") return `the ${role === "parent" ? "parent supervisor" : "viewer"} is ${unit ? `${unit.state}${unit.result ? ` (${unit.result})` : ""}` : "not reported yet"}`;
	}
	return undefined;
}

/** ≤ 60 s for `notReady` to clear; why not otherwise. */
async function daemonReady(ctx: BackendContext): Promise<string | undefined> {
	const paths = daemonPaths(ctx.config.home);
	for (let waited = 0; ; waited += 1_000) {
		const why = notReady(ctx, paths);
		if (!why || waited >= READY_WAIT_MS) return why && `${why} after ${READY_WAIT_MS / 1000}s`;
		await ctx.ports.sleep(1_000);
	}
}

function logTail(ctx: BackendContext): string {
	const lines = (ctx.ports.read(daemonPaths(ctx.config.home).log) ?? "").split("\n").filter(Boolean).slice(-5);
	return lines.length ? `; cp-daemon log says: ${lines.join(" | ")}` : "; see cp-daemon log";
}

/**
 * Linger (moved verbatim from install.ts): the user manager, so the unit, runs without a login session. cp-install
 * runs it before writing anything, so a refusal leaves no new data/daemon.json or cp-daemon.service behind.
 */
export function linger(ctx: Pick<BackendContext, "ports" | "dry" | "step">): boolean {
	const { ports, dry, step } = ctx;
	const user = ports.env.USER ?? ports.env.LOGNAME ?? userInfo().username;
	const shown = ports.run("loginctl", ["show-user", user, "--property=Linger"]).stdout.trim();
	if (shown === "Linger=yes") step("ok", "linger", `on for ${user}`);
	else if (dry) step("changed", "linger", `would run loginctl enable-linger ${user}`);
	else if (ports.run("loginctl", ["enable-linger", user]).status === 0) step("changed", "linger", `enabled for ${user}`);
	else {
		step("fail", "linger", `loginctl enable-linger refused; run: sudo loginctl enable-linger ${user}`);
		return false;
	}
	return true;
}

/**
 * M1's preflight, before cp-install writes anything: why the legacy home cannot migrate now (a hand-written
 * unit, an update run in flight, a recorded update phase), or undefined. Drop-ins and drains are reported.
 */
export function legacyPreflight(ctx: BackendContext): string | undefined {
	const { ports, step } = ctx;
	const present = legacyPresent(ports, ctx.unitDir);
	const hand = present.filter((name) => !(ports.read(unitFile(ctx, name)) ?? "").includes(GENERATED));
	if (hand.length) return `${hand.map((name) => unitFile(ctx, name)).join(", ")} not written by cp-install; migrate by hand (docs/service.md §Migration, M2)`;
	if (systemctl(ctx, "is-active", UPDATE).stdout.trim() === "active") return `an update run is in flight (${UPDATE} is active); rerun after it finishes`;
	const paths = daemonPaths(ctx.config.home);
	const phase = parse<{ phase?: unknown }>(ports.read(paths.update))?.phase;
	if (phase !== undefined && phase !== "idle" && !ctx.force) return `${paths.update} records phase ${String(phase)}; rerun after it is idle, or with --force (the first cp-daemon update run recovers it)`;
	const environment = systemctl(ctx, "show", VIEW, "--property=Environment", "--value").stdout;
	const dropIn = [...environment.matchAll(/(?:^|\s)CP_VIEWER_HOST=(\S+)/g)].at(-1)?.[1];
	if (dropIn !== undefined && dropIn !== ctx.config.viewer_host) step("skip", "viewer-host", `a drop-in on ${VIEW} sets CP_VIEWER_HOST=${dropIn}; cp-daemon does not read it: to keep that address rerun with --viewer-host ${dropIn} --force, then remove the drop-in yourself`);
	if (ports.exists(join(paths.stateDir, "drain.json"))) step("skip", "migrate", "state/drain.json exists: the fleet stays drained; migration never touches the parent host or its workers");
	return undefined;
}

/** M1 (`legacyPreflight` passed, `data/daemon.json` and the thin unit written): legacy units → cp-daemon.service. */
async function migrateLegacy(ctx: BackendContext): Promise<void> {
	const { ports, step } = ctx;
	const present = legacyPresent(ports, ctx.unitDir);
	const timers = [HEALTH_TIMER, UPDATE_TIMER];
	// S8 only: a refused or rolled-back M1 leaves these as they were. Never stopped (cp-operator.service's ExecStop
	// would kill the live tmux operator session); a hand-written one stays.
	const retired = (ctx.retire ?? []).filter((name) => (ports.read(unitFile(ctx, name)) ?? "").includes(GENERATED));
	if (ctx.dry) {
		step("changed", "migrate", `would: systemctl --user daemon-reload; disable --now ${timers.join(" ")}; re-check ${UPDATE}; disable --now ${VIEW}; disable --now ${PARENT} (KillMode=process: the host and workers keep running); enable --now ${DAEMON_UNIT}; verify ≤ ${READY_WAIT_MS / 1000}s; then remove ${[...present, ...retired].join(", ")}`);
		return;
	}
	const undoConfig = (): void => {
		ports.remove(unitFile(ctx, DAEMON_UNIT));
		ports.remove(daemonPaths(ctx.config.home).config);
		systemctl(ctx, "daemon-reload");
	};
	systemctl(ctx, "daemon-reload");
	systemctl(ctx, "disable", "--now", ...timers);
	if (systemctl(ctx, "is-active", UPDATE).stdout.trim() === "active") {
		systemctl(ctx, "enable", "--now", ...timers);
		undoConfig();
		return step("fail", "migrate", `an update run started meanwhile (${UPDATE} is active): the timers are back, nothing else changed; rerun after it finishes`);
	}
	systemctl(ctx, "disable", "--now", VIEW);
	systemctl(ctx, "disable", "--now", PARENT);
	const enabled = systemctl(ctx, "enable", "--now", DAEMON_UNIT);
	const why = failed(enabled, `systemctl --user enable --now ${DAEMON_UNIT}`) ?? (await daemonReady(ctx));
	if (why) {
		const tail = logTail(ctx);
		systemctl(ctx, "disable", "--now", DAEMON_UNIT);
		undoConfig();
		systemctl(ctx, "enable", "--now", ...LEGACY_ENABLED);
		const states = await Promise.all([PARENT, VIEW].map(async (unit) => `${unit} ${await activeWithin(unit, ctx)}`));
		return step("fail", "migrate", `${why}; rolled back: ${DAEMON_UNIT} removed, the legacy units re-enabled (${states.join(", ")})${tail}`);
	}
	for (const name of [...present, ...retired]) ports.remove(unitFile(ctx, name));
	systemctl(ctx, "daemon-reload");
	step("changed", "migrate", `${DAEMON_UNIT} runs the parent supervisor and the viewer; removed ${[...present, ...retired].join(", ")} (the parent host kept running${retired.length ? "; the operator units never stopped" : ""})`);
}

/**
 * The legacy rollback's verify: poll `is-active` while the unit is still starting, up to `tries` seconds. A
 * Type=simple unit reads `active` right after fork, so `active` counts only when it still is `settleMs` later
 * with the same `NRestarts`.
 */
async function activeWithin(unit: string, ctx: BackendContext, tries = 30, settleMs = 3_000): Promise<string> {
	const read = (...args: string[]) => systemctl(ctx, ...args, unit).stdout.trim();
	const restarts = () => read("show", "--property=NRestarts", "--value");
	for (let attempt = 1; ; attempt++) {
		let state = read("is-active") || "unknown";
		if (state === "active") {
			const before = restarts();
			await ctx.ports.sleep(settleMs);
			state = read("is-active") || "unknown";
			if (state === "active" && restarts() === before) return state;
			if (state === "active") state = "restarting";
		}
		if (!["activating", "restarting"].includes(state) || attempt >= tries) return state;
		await ctx.ports.sleep(1_000);
	}
}

/**
 * cp-install's start, after it wrote `data/daemon.json` (and the thin unit) and linger is on. systemd: a legacy
 * home migrates (M1), else `enable [--now]` and wait until ready; a changed unit or config restarts the daemon.
 * detached: `cp-daemon start` (restart when changed), the reboot command, the opt-in crontab line.
 */
export async function activate(ctx: BackendContext): Promise<void> {
	const { config, dry, noStart, step } = ctx;
	if (config.backend === "systemd") {
		const legacy = legacyPresent(ctx.ports, ctx.unitDir);
		// --no-start on a legacy home: no migration, and no enable either (both would start at boot and fight over the port).
		if (legacy.length > 0 && noStart) return step("skip", "migrate", `${legacy.join(", ")} still run this home, untouched (--no-start); rerun without --no-start to migrate`);
		if (legacy.length > 0) return migrateLegacy(ctx);
		if (dry) return step("changed", "enable", `would run systemctl --user daemon-reload, enable${noStart ? "" : " --now"} ${DAEMON_UNIT}${ctx.changed && !noStart ? `, try-restart ${DAEMON_UNIT}` : ""}`);
		systemctl(ctx, "daemon-reload");
		const enable = failed(systemctl(ctx, "enable", ...(noStart ? [] : ["--now"]), DAEMON_UNIT), `systemctl --user enable ${DAEMON_UNIT}`);
		if (enable) return step("fail", "enable", enable);
		if (noStart) return step("ok", "enable", `${DAEMON_UNIT} enabled, not started (--no-start); start it: ${startCommand(config)}`);
		// The outer reads the unit and data/daemon.json once: a changed one restarts it (the host and workers stay up).
		if (ctx.changed) systemctl(ctx, "try-restart", DAEMON_UNIT);
		const why = await daemonReady(ctx);
		return step(why ? "fail" : "ok", "enable", why ? `${why}${logTail(ctx)}; journalctl --user -u ${DAEMON_UNIT} -n 20` : `${DAEMON_UNIT} is active: the parent supervisor and the viewer run`);
	}
	const reboot = `after a reboot run: ${rebootCommand(config)}`;
	if (noStart) step("skip", "daemon", `not started (--no-start); start it now and ${reboot}`);
	else if (dry) step("changed", "daemon", `would run cp-daemon ${ctx.changed ? "restart" : "start"} (detached); ${reboot}`);
	else {
		const running = daemonCli(ctx, "status").status === 0;
		const verb = running ? (ctx.changed ? "restart" : undefined) : "start";
		const result = verb ? daemonCli(ctx, verb) : undefined;
		if (result && result.status !== 0) step("fail", "daemon", `cp-daemon ${verb} failed: ${(result.stdout + result.stderr).trim().split("\n").slice(-5).join(" | ") || `exit ${result.status}`}`);
		else step(verb ? "changed" : "ok", "daemon", `${verb === "start" ? "started" : verb === "restart" ? "restarted onto the new config" : "running"} (detached); ${reboot}`);
	}
	if (ctx.crontab) crontab(ctx);
}

const cronMarker = (home: string) => `# cp-daemon ${home}`;

/** `crontab -l`'s lines, or undefined when crontab is not usable here (exit 1 "no crontab for" is an empty one). */
function cronLines(ctx: BackendContext): string[] | undefined {
	const listed = ctx.ports.run("crontab", ["-l"]);
	if (listed.status === 0) return listed.stdout.split("\n").filter(Boolean);
	return listed.status === 1 && /no crontab for/i.test(listed.stderr) ? [] : undefined;
}

/** Through a file (`crontab <file>`, POSIX), never stdin. */
function writeCron(ctx: BackendContext, lines: string[]): string | undefined {
	const tmp = join(daemonPaths(ctx.config.home).stateDir, "daemon-crontab.tmp");
	ctx.ports.write(tmp, lines.length ? `${lines.join("\n")}\n` : "", 0o600);
	const result = ctx.ports.run("crontab", [tmp]);
	ctx.ports.remove(tmp);
	return failed(result, `crontab ${tmp}`);
}

/** `--crontab`: one marked `@reboot` line for this home, replacing an older one of ours. */
function crontab(ctx: BackendContext): void {
	const line = `@reboot ${rebootCommand(ctx.config)} >/dev/null 2>&1 ${cronMarker(ctx.config.home)}`;
	const lines = cronLines(ctx);
	if (!lines) return ctx.step("skip", "crontab", `crontab -l does not work here; add this line yourself (crontab -e): ${line}`);
	if (lines.includes(line)) return ctx.step("ok", "crontab", "the @reboot line is in your crontab");
	if (ctx.dry) return ctx.step("changed", "crontab", `would add: ${line}`);
	const error = writeCron(ctx, [...lines.filter((row) => !row.endsWith(cronMarker(ctx.config.home))), line]);
	ctx.step(error ? "fail" : "changed", "crontab", error ?? `added: ${line}`);
}

/** Uninstall: stop the daemon (never the host), remove the generated thin and legacy unit files. */
export function deactivate(ctx: BackendContext): void {
	const { ports, dry, step } = ctx;
	if (ctx.config.backend === "detached") {
		if (!dry && ports.exists(daemonPaths(ctx.config.home).config)) {
			const stopped = daemonCli(ctx, "stop");
			step(stopped.status === 0 ? "ok" : "fail", "uninstall", stopped.status === 0 ? "cp-daemon stopped (the parent host and workers keep running)" : `cp-daemon stop failed: ${(stopped.stdout + stopped.stderr).trim()}`);
		}
		const lines = cronLines(ctx);
		if (lines?.some((row) => row.endsWith(cronMarker(ctx.config.home)))) {
			const error = dry ? undefined : writeCron(ctx, lines.filter((row) => !row.endsWith(cronMarker(ctx.config.home))));
			step(error ? "fail" : "changed", "uninstall", error ?? "removed the cp-daemon @reboot line from your crontab");
		}
		return;
	}
	const generated = (name: string) => (ports.read(unitFile(ctx, name)) ?? "").includes(GENERATED);
	const enabled = [DAEMON_UNIT, ...LEGACY_ENABLED].filter((name) => generated(name));
	if (!dry && enabled.length) systemctl(ctx, "disable", "--now", ...enabled);
	for (const name of [DAEMON_UNIT, ...LEGACY_UNITS]) {
		const path = unitFile(ctx, name);
		if (!ports.exists(path)) continue;
		if (!generated(name)) step("skip", "uninstall", `${path} was not written by cp-install; left in place`);
		else {
			if (!dry) ports.remove(path);
			step("changed", "uninstall", `removed ${path}`);
		}
	}
	if (!dry) systemctl(ctx, "daemon-reload");
}

// ---------------------------------------------------------------------------
// /doctor (status.ts)
// ---------------------------------------------------------------------------

export interface BackendFinding { check: string; severity: "ok" | "warn" | "error"; what: string; detail?: string; fix?: string }
export type Probe = { alive(pid: number): boolean; argsOf(pid: number): string | undefined };
type FindRun = (command: string, args: string[], cwd: string) => { status: number | null; stdout: string };

const fileText = (path: string): string | undefined => (existsSync(path) ? readFileSync(path, "utf8") : undefined);

/**
 * `service.daemon` (when `data/daemon.json` exists) and `service.legacy_units` (when a legacy unit file is
 * present: warn, never error — verify after an update rejects only errors). Nothing installed → nothing.
 */
export function daemonFindings(run: FindRun, home: string, unitDir: string, probe: Probe = { alive: pidAlive, argsOf: psArgs }): BackendFinding[] {
	const findings: BackendFinding[] = [];
	const paths = daemonPaths(home);
	let config: DaemonConfig | undefined;
	try {
		config = readDaemonConfig(paths.config);
	} catch (error) {
		findings.push({ check: "service.daemon", severity: "warn", what: (error as Error).message, fix: "rerun cp-install --force (it rewrites data/daemon.json)" });
	}
	if (config) findings.push(daemonFinding(run, home, paths, config, probe));
	const legacy = LEGACY_UNITS.filter((name) => existsSync(join(unitDir, name)));
	if (legacy.length) {
		findings.push({
			check: "service.legacy_units",
			severity: "warn",
			what: `${legacy.length} legacy unit(s) in ${unitDir}`,
			detail: legacy.join(", "),
			fix: "this home still runs the legacy cp-* units and auto-update records migration_required: rerun cp-install to move it to cp-daemon (docs/service.md §Migration)",
		});
	}
	return findings;
}

function daemonFinding(run: FindRun, home: string, paths: DaemonPaths, config: DaemonConfig, probe: Probe): BackendFinding {
	const check = "service.daemon";
	let lock: LockRecord | undefined;
	try {
		lock = readJson<LockRecord>(paths.lock);
	} catch {
		lock = undefined;
	}
	const running = config.backend === "systemd" ? run("systemctl", ["--user", "is-active", DAEMON_UNIT], home).stdout.trim() === "active" : sameProcess(lock?.pid, OUTER_ARGV, probe);
	if (!running) return { check, severity: "warn", what: `cp-daemon is not running (${config.backend} backend)`, fix: `start it: ${startCommand(config)}; then cp-daemon status` };
	let state: DaemonState | undefined;
	let runtime: RuntimeRecord | undefined;
	try {
		state = readJson<DaemonState>(paths.state);
		runtime = readJson<RuntimeRecord>(paths.runtime);
	} catch (error) {
		return { check, severity: "warn", what: `cp-daemon runs, but its records are unreadable: ${(error as Error).message}`, fix: "cp-daemon log, then cp-daemon reload" };
	}
	const inner = state?.inner;
	if (inner && ["crash_looping", "failed", "not_ready"].includes(inner.state)) return { check, severity: "warn", what: `cp-daemon's runtime is ${inner.state}${inner.detail ? `: ${inner.detail}` : ""}`, fix: "cp-daemon log, then cp-daemon reload" };
	const parent = runtime?.units.parent;
	if (parent?.state === "failed") {
		return parent.result === "exit-code"
			? { check, severity: "warn", what: "cp-daemon: the parent supervisor stopped: no parent model (exit 78)", fix: "pin a model: cp-install --parent-model <provider/model> --force" }
			: { check, severity: "warn", what: `cp-daemon: the parent supervisor is failed (${parent.result ?? "failed"})${parent.result === "start-limit-hit" ? " — a crash loop" : ""}`, fix: "cp-daemon log, then cp-daemon reload" };
	}
	const viewer = runtime?.units.viewer;
	if (viewer && !["running", "starting", "held"].includes(viewer.state)) return { check, severity: "warn", what: `cp-daemon: the viewer is ${viewer.state}`, fix: "cp-daemon log (it binds CP_VIEWER_HOST, else `tailscale ip -4`); pin one with cp-install --viewer-host <ip> --force" };
	let onDisk: string | undefined;
	try {
		onDisk = outerHash(join(config.app, "src/service"));
	} catch {
		onDisk = undefined; // the checkout cannot be hashed: nothing to compare
	}
	if (state && onDisk && state.outer_hash !== onDisk) return { check, severity: "warn", what: `cp-daemon's outer (${state.outer_hash.slice(0, 12)}) predates the code on disk (${onDisk.slice(0, 12)}); a reload never replaces it`, fix: "cp-daemon restart at a quiet point (the parent host and workers keep running)" };
	return { check, severity: "ok", what: `cp-daemon running${state ? ` pid ${state.pid}` : ""} (${config.backend}): parent ${parent?.state ?? "unknown"}, viewer ${viewer?.state ?? "unknown"}` };
}

/**
 * True when a missing viewer is a fault: cp-daemon runs one (`data/daemon.json`) and no update holds it, or a
 * legacy cp-view.service is enabled.
 */
export function viewerExpected(run: FindRun, home: string, unitDir: string): boolean {
	const paths = daemonPaths(home);
	if (existsSync(paths.config)) return parse<RuntimeRecord>(fileText(paths.runtime))?.units?.viewer?.state !== "held";
	if (!(fileText(join(unitDir, VIEW)) ?? "").includes(GENERATED)) return false;
	return run("systemctl", ["--user", "is-enabled", VIEW], home).stdout.trim() === "enabled";
}
