/**
 * cp-txbb: cp-daemon's backend port over fakes — no systemctl, loginctl, crontab or daemon process is
 * ever run. M1 (legacy units → cp-daemon.service) is driven through a fake user manager.
 */
import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { activate, type BackendContext, type BackendPorts, DAEMON_UNIT, daemonFindings, deactivate, detectBackend, LEGACY_UNITS, legacyPreflight, viewerExpected } from "../src/service/daemon-backend.ts";
import { type DaemonConfig, daemonPaths, OUTER_SOURCES, outerHash } from "../src/service/daemon-files.ts";

const HOME = "/h/home";
const UNIT_DIR = "/h/units";
const PATHS = daemonPaths(HOME);
const GENERATED = "# Generated by cp-install (pi-command-post); edits are refused on reinstall without --force.\n";

interface WorldOptions {
	backend?: "systemd" | "detached";
	legacy?: boolean;
	comesUp?: boolean;
	noStart?: boolean;
	changed?: boolean;
	dry?: boolean;
	force?: boolean;
	crontab?: boolean;
	/** `cp-daemon status` exit (detached). */
	running?: boolean;
	/** The nth `is-active cp-update.service` answers active (1-based). */
	updateActiveAt?: number;
}

function world(options: WorldOptions = {}) {
	const files = new Map<string, string>();
	const calls: string[] = [];
	const steps: Array<[string, string, string]> = [];
	const active = new Set<string>();
	let updateChecks = 0;
	const config: DaemonConfig = { schema_version: 1, generated_by: "cp-install", backend: options.backend ?? "systemd", node: "/opt/node/bin/node", app: "/srv/app", home: HOME, path: "/opt/node/bin:/usr/bin", port: 7300 };
	files.set(PATHS.config, JSON.stringify(config));
	if (config.backend === "systemd") files.set(join(UNIT_DIR, DAEMON_UNIT), GENERATED);
	if (options.legacy) {
		for (const name of LEGACY_UNITS) files.set(join(UNIT_DIR, name), GENERATED);
		for (const name of ["cp-parent.service", "cp-view.service", "cp-health.timer", "cp-update.timer"]) active.add(name);
	}
	const comeUp = (): void => {
		if (options.comesUp === false) return;
		files.set(PATHS.state, JSON.stringify({ pid: 1, inner: { state: "ready" } }));
		files.set(PATHS.runtime, JSON.stringify({ units: { parent: { state: "running" }, viewer: { state: "running" } } }));
	};
	const ok = (stdout = "") => ({ status: 0, stdout, stderr: "" });
	const ports: BackendPorts = {
		env: { USER: "u" },
		read: (path) => files.get(path),
		write: (path, text) => void files.set(path, text),
		exists: (path) => files.has(path),
		remove: (path) => void files.delete(path),
		sleep: async () => {},
		run: (command, args) => {
			const line = [command, ...args].join(" ");
			calls.push(line);
			if (command === "loginctl") return ok("Linger=yes");
			if (command === "/opt/node/bin/node") {
				const verb = args[1];
				if (verb === "status") return { status: options.running ? 0 : 3, stdout: "", stderr: "" };
				return ok(`cp-daemon ${verb}: ok`);
			}
			if (command === "crontab") return args[0] === "-l" ? { status: 1, stdout: "", stderr: "no crontab for u" } : ok();
			const [, verb, ...rest] = args;
			const units = rest.filter((word) => !word.startsWith("--"));
			if (verb === "is-system-running") return ok("running");
			if (verb === "is-active") {
				const unit = units[0] as string;
				if (unit === "cp-update.service") return ok(++updateChecks === options.updateActiveAt ? "active" : "inactive");
				return ok(active.has(unit) ? "active" : "inactive");
			}
			if (verb === "show") return ok(units.includes("cp-view.service") && args.includes("--property=Environment") ? "CP_VIEWER_HOST=100.64.0.9" : "0");
			if (verb === "enable" && rest.includes("--now")) {
				for (const unit of units) active.add(unit);
				if (units.includes(DAEMON_UNIT)) comeUp();
			}
			if (verb === "disable" && rest.includes("--now")) for (const unit of units) active.delete(unit);
			if (verb === "try-restart") comeUp();
			return ok();
		},
	};
	const ctx: BackendContext = {
		ports,
		config,
		unitDir: UNIT_DIR,
		dry: options.dry ?? false,
		force: options.force ?? false,
		noStart: options.noStart ?? false,
		crontab: options.crontab ?? false,
		changed: options.changed ?? false,
		step: (status, name, detail) => void steps.push([status, name, detail]),
	};
	const systemctl = () => calls.filter((line) => line.startsWith("systemctl"));
	return { ctx, files, calls, steps, active, systemctl, text: () => steps.map((step) => step.join(" ")).join("\n") };
}

test("detectBackend: a running or degraded user manager is systemd, anything else detached", () => {
	for (const [state, backend] of [["running", "systemd"], ["degraded", "systemd"], ["offline", "detached"], ["", "detached"]] as const) {
		assert.equal(detectBackend(() => ({ status: state ? 0 : 1, stdout: `${state}\n`, stderr: "" })).backend, backend, state);
	}
});

test("systemd, fresh home: daemon-reload, enable --now cp-daemon.service, wait until ready; a changed unit or config try-restarts", async () => {
	const fresh = world();
	await activate(fresh.ctx);
	assert.deepEqual(fresh.systemctl(), ["systemctl --user daemon-reload", `systemctl --user enable --now ${DAEMON_UNIT}`, `systemctl --user is-active ${DAEMON_UNIT}`]);
	assert.match(fresh.text(), /^ok enable cp-daemon\.service is active/m);
	const changed = world({ changed: true });
	await activate(changed.ctx);
	assert.ok(changed.systemctl().includes(`systemctl --user try-restart ${DAEMON_UNIT}`));
	const down = world({ comesUp: false });
	await activate(down.ctx);
	assert.match(down.text(), /^fail enable no .*daemon\.json yet after 60s/m);
});

test("--no-start, systemd: enable without --now, nothing started, no migration", async () => {
	const w = world({ noStart: true, changed: true });
	await activate(w.ctx);
	assert.deepEqual(w.systemctl(), ["systemctl --user daemon-reload", `systemctl --user enable ${DAEMON_UNIT}`]);
	assert.ok(!w.calls.some((line) => /--now|try-restart|start /.test(line)), w.calls.join("\n"));
	assert.match(w.text(), /enabled, not started \(--no-start\)/);
});

test("--no-start, detached: no cp-daemon start, the reboot command printed", async () => {
	const w = world({ backend: "detached", noStart: true });
	await activate(w.ctx);
	assert.deepEqual(w.calls, []);
	assert.match(w.text(), /not started \(--no-start\).*after a reboot run: "\/opt\/node\/bin\/node" "\/srv\/app\/src\/service\/daemon\.ts" start --home "\/h\/home"/);
});

test("--no-start, legacy home: no migration call, no enable, the legacy units left running and in place", async () => {
	const w = world({ legacy: true, noStart: true });
	await activate(w.ctx);
	assert.deepEqual(w.systemctl(), []);
	for (const name of LEGACY_UNITS) assert.ok(w.files.has(join(UNIT_DIR, name)), name);
	assert.deepEqual([...w.active].sort(), ["cp-health.timer", "cp-parent.service", "cp-update.timer", "cp-view.service"]);
	assert.match(w.text(), /^skip migrate .*untouched \(--no-start\); rerun without --no-start to migrate/m);
});

test("detached: starts a stopped daemon, restarts a running one onto a changed config, leaves an unchanged one", async () => {
	const stopped = world({ backend: "detached" });
	await activate(stopped.ctx);
	assert.deepEqual(stopped.calls, ["/opt/node/bin/node /srv/app/src/service/daemon.ts status --home /h/home", "/opt/node/bin/node /srv/app/src/service/daemon.ts start --home /h/home"]);
	assert.match(stopped.text(), /^changed daemon started \(detached\); after a reboot run: /m);
	const changed = world({ backend: "detached", running: true, changed: true });
	await activate(changed.ctx);
	assert.equal(changed.calls.at(-1), "/opt/node/bin/node /srv/app/src/service/daemon.ts restart --home /h/home");
	const same = world({ backend: "detached", running: true });
	await activate(same.ctx);
	assert.equal(same.calls.length, 1);
	assert.match(same.text(), /^ok daemon running \(detached\)/m);
});

test("--crontab (detached): one marked @reboot line through a file, never stdin", async () => {
	const w = world({ backend: "detached", running: true, crontab: true });
	await activate(w.ctx);
	const tmp = join(PATHS.stateDir, "daemon-crontab.tmp");
	assert.deepEqual(w.calls.slice(1), ["crontab -l", `crontab ${tmp}`]);
	assert.equal(w.files.has(tmp), false, "the temp file is removed");
	assert.match(w.text(), /^changed crontab added: @reboot "\/opt\/node\/bin\/node" .* start --home "\/h\/home" >\/dev\/null 2>&1 # cp-daemon \/h\/home$/m);
});

test("M1 preflight: a hand-written unit, an update run in flight or a recorded update phase refuses; --force passes the phase; the drop-in is reported", () => {
	const hand = world({ legacy: true });
	hand.files.set(join(UNIT_DIR, "cp-view.service"), "[Service]\nExecStart=/bin/true\n");
	assert.match(legacyPreflight(hand.ctx) ?? "", /cp-view\.service not written by cp-install; migrate by hand/);
	const busy = world({ legacy: true, updateActiveAt: 1 });
	assert.match(legacyPreflight(busy.ctx) ?? "", /an update run is in flight/);
	const phase = world({ legacy: true });
	phase.files.set(PATHS.update, JSON.stringify({ phase: "merging" }));
	assert.match(legacyPreflight(phase.ctx) ?? "", /records phase merging; rerun after it is idle, or with --force/);
	const forced = world({ legacy: true, force: true });
	forced.files.set(PATHS.update, JSON.stringify({ phase: "merging" }));
	assert.equal(legacyPreflight(forced.ctx), undefined);
	assert.match(forced.text(), /sets CP_VIEWER_HOST=100\.64\.0\.9; cp-daemon does not read it: to keep that address rerun with --viewer-host 100\.64\.0\.9 --force/);
});

test("M1: timers off, update re-checked, viewer then parent off, cp-daemon on and ready, then the legacy files go", async () => {
	const w = world({ legacy: true });
	await activate(w.ctx);
	assert.deepEqual(w.systemctl().slice(0, 7), [
		"systemctl --user daemon-reload",
		"systemctl --user disable --now cp-health.timer cp-update.timer",
		"systemctl --user is-active cp-update.service",
		"systemctl --user disable --now cp-view.service",
		"systemctl --user disable --now cp-parent.service",
		`systemctl --user enable --now ${DAEMON_UNIT}`,
		`systemctl --user is-active ${DAEMON_UNIT}`,
	]);
	assert.equal(w.systemctl().at(-1), "systemctl --user daemon-reload");
	for (const name of LEGACY_UNITS) assert.equal(w.files.has(join(UNIT_DIR, name)), false, name);
	assert.ok(w.files.has(join(UNIT_DIR, DAEMON_UNIT)) && w.files.has(PATHS.config));
	assert.deepEqual([...w.active], [DAEMON_UNIT]);
	assert.match(w.text(), /^changed migrate cp-daemon\.service runs the parent supervisor and the viewer/m);
});

test("M1 rollback: a daemon not ready in 60 s is disabled, its unit and data/daemon.json removed, the legacy units re-enabled", async () => {
	const w = world({ legacy: true, comesUp: false });
	w.files.set(PATHS.log, "line one\nboom: EADDRINUSE\n");
	await activate(w.ctx);
	const tail = w.systemctl().slice(w.systemctl().indexOf(`systemctl --user disable --now ${DAEMON_UNIT}`));
	assert.deepEqual(tail.slice(0, 3), [`systemctl --user disable --now ${DAEMON_UNIT}`, "systemctl --user daemon-reload", "systemctl --user enable --now cp-parent.service cp-view.service cp-health.timer cp-update.timer"]);
	assert.equal(w.files.has(join(UNIT_DIR, DAEMON_UNIT)), false);
	assert.equal(w.files.has(PATHS.config), false, "data/daemon.json removed: the legacy updater records migration_required again");
	for (const name of LEGACY_UNITS) assert.ok(w.files.has(join(UNIT_DIR, name)), name);
	assert.match(w.text(), /^fail migrate .* after 60s; rolled back: .*cp-parent\.service active, cp-view\.service active.*boom: EADDRINUSE/m);
});

test("M1: an update run that starts while the timers go off puts the timers back and changes nothing else", async () => {
	const w = world({ legacy: true, updateActiveAt: 1 });
	await activate(w.ctx);
	assert.ok(w.systemctl().includes("systemctl --user enable --now cp-health.timer cp-update.timer"));
	assert.ok(!w.systemctl().some((line) => line.includes("cp-parent.service") || line.includes(DAEMON_UNIT)));
	assert.equal(w.files.has(PATHS.config), false);
	assert.match(w.text(), /^fail migrate an update run started meanwhile/m);
});

test("M1 --dry-run: says what it would do, calls nothing but linger", async () => {
	const w = world({ legacy: true, dry: true });
	await activate(w.ctx);
	assert.deepEqual(w.systemctl(), []);
	assert.match(w.text(), /^changed migrate would: systemctl --user daemon-reload; disable --now cp-health\.timer cp-update\.timer/m);
});

test("deactivate, systemd: disables and removes the generated units, leaves a hand-written one", () => {
	const w = world({ legacy: true });
	w.files.set(join(UNIT_DIR, "cp-health.service"), "[Service]\n");
	deactivate(w.ctx);
	assert.equal(w.systemctl()[0], `systemctl --user disable --now ${DAEMON_UNIT} cp-parent.service cp-view.service cp-health.timer cp-update.timer`);
	assert.ok(w.files.has(join(UNIT_DIR, "cp-health.service")));
	assert.equal(w.files.has(join(UNIT_DIR, DAEMON_UNIT)), false);
	assert.match(w.text(), /^skip uninstall .*cp-health\.service was not written by cp-install/m);
});

test("daemonFindings: nothing installed is silent; legacy files warn; not running, a failed parent and a stale outer warn; healthy is ok", (t) => {
	const dir = mkdtempSync(join(tmpdir(), "cp-backend-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	const home = join(dir, "home");
	const unitDir = join(dir, "units");
	const app = join(dir, "app");
	const paths = daemonPaths(home);
	for (const sub of [paths.dataDir, paths.stateDir, unitDir, join(app, "src/service")]) mkdirSync(sub, { recursive: true });
	const run = () => ({ status: 0, stdout: "" });
	const probe = { alive: (pid: number) => pid === 4242, argsOf: () => "/n /srv/app/src/service/daemon.ts run --home h" };
	assert.deepEqual(daemonFindings(run, home, unitDir, probe), []);
	assert.equal(viewerExpected(run, home, unitDir), false);
	writeFileSync(join(unitDir, "cp-parent.service"), GENERATED);
	const legacy = daemonFindings(run, home, unitDir, probe);
	assert.deepEqual(legacy.map((f) => [f.check, f.severity]), [["service.legacy_units", "warn"]]);
	assert.match(legacy[0]?.fix ?? "", /rerun cp-install/);
	rmSync(join(unitDir, "cp-parent.service"));

	writeFileSync(paths.config, JSON.stringify({ schema_version: 1, generated_by: "cp-install", backend: "detached", node: "/n", app, home, path: "/bin", port: 7300 }));
	assert.equal(viewerExpected(run, home, unitDir), true);
	const down = daemonFindings(run, home, unitDir, probe);
	assert.deepEqual(down.map((f) => [f.check, f.severity]), [["service.daemon", "warn"]]);
	assert.match(down[0]?.fix ?? "", /start it: "\/n" .* start --home/);

	for (const name of OUTER_SOURCES) writeFileSync(join(app, "src/service", name), name);
	writeFileSync(paths.lock, JSON.stringify({ pid: 4242, started_at: "x", argv: "daemon.ts run" }));
	const healthy = { pid: 4242, outer_hash: outerHash(join(app, "src/service")), inner: { state: "ready" } };
	writeFileSync(paths.state, JSON.stringify(healthy));
	writeFileSync(paths.runtime, JSON.stringify({ units: { parent: { state: "running" }, viewer: { state: "held" } } }));
	assert.deepEqual(daemonFindings(run, home, unitDir, probe).map((f) => f.severity), ["ok"]);

	writeFileSync(paths.runtime, JSON.stringify({ units: { parent: { state: "failed", result: "start-limit-hit" }, viewer: { state: "running" } } }));
	assert.match(daemonFindings(run, home, unitDir, probe)[0]?.what ?? "", /parent supervisor is failed \(start-limit-hit\) — a crash loop/);

	writeFileSync(paths.runtime, JSON.stringify({ units: { parent: { state: "running" }, viewer: { state: "running" } } }));
	writeFileSync(paths.state, JSON.stringify({ ...healthy, outer_hash: "0".repeat(64) }));
	const stale = daemonFindings(run, home, unitDir, probe)[0];
	assert.equal(stale?.severity, "warn");
	assert.match(stale?.what ?? "", /predates the code on disk/);
	assert.match(stale?.fix ?? "", /cp-daemon restart/);
});
