/** cp-daemon P2: the unit text and the operator wrapper (src/service/units.ts). */
import assert from "node:assert/strict";
import { execFileSync, spawnSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { LEGACY_UNITS } from "../src/service/daemon-backend.ts";
import { unitNode } from "../src/service/status.ts";
import { DAEMON_UNIT, HEALTH_TIMER, HEALTH_UNIT, installTargets, OPERATOR_RESUME_UNIT, OPERATOR_UNIT, OPERATOR_WRAPPER, PARENT_UNIT, renderDaemonUnit, renderOperatorWrapper, renderUnits, unitParentModel, unitViewerHost, UPDATE_TIMER, UPDATE_UNIT, VIEW_UNIT, wrapperModels, wrapperViewerHost } from "../src/service/units.ts";
import { operatorWrapperPath } from "../src/viewer/launchers.ts";

test("the herdr Start runs the wrapper cp-install writes: operatorWrapperPath equals installTargets().binDir + OPERATOR_WRAPPER", () => {
	for (const env of [{ HOME: "/home/u" }, { HOME: "/home/u with space" }, { HOME: "" }]) assert.equal(operatorWrapperPath(env), join(installTargets(env).binDir, OPERATOR_WRAPPER));
});

const input = { node: "/opt/node/bin/node", app: "/home/u/.pi-command-post/app", home: "/home/u/.pi-command-post", path: "/opt/node/bin:/usr/bin", port: 8766 };

test("cp-parent.service: attach-first supervisor, crash-loop stop, no-model stop, KillMode=process, CP_HOME", () => {
	const text = renderUnits({ ...input, parentModel: "anthropic/claude-opus-4-6" })[PARENT_UNIT]!;
	for (const line of [
		'ExecStart="/opt/node/bin/node" "/home/u/.pi-command-post/app/src/service/supervise.ts"',
		"WorkingDirectory=/home/u/.pi-command-post",
		'Environment="CP_HOME=/home/u/.pi-command-post"',
		'Environment="CP_MODE=multi"',
		'Environment="PATH=/opt/node/bin:/usr/bin"',
		'Environment="CP_VIEWER_PORT=8766"',
		'Environment="CP_PARENT_MODEL=anthropic/claude-opus-4-6"',
		"Restart=on-failure", "RestartSec=5", "RestartSteps=5", "RestartMaxDelaySec=300",
		"RestartPreventExitStatus=78", "KillMode=process", "TimeoutStopSec=10",
		"StartLimitIntervalSec=1800", "StartLimitBurst=6", "WantedBy=default.target",
	]) assert.ok(text.split("\n").includes(line), `missing ${line}\n${text}`);
	assert.equal(unitNode(text), "/opt/node/bin/node");
	assert.doesNotMatch(renderUnits(input)[PARENT_UNIT]!, /CP_PARENT_MODEL/, "no model named → none recorded");
});

test("cp-daemon.service (cp-txbb): the thin unit runs `daemon.ts run` in the foreground; no viewer host or model in it", () => {
	const text = renderDaemonUnit(input);
	for (const line of [
		"# Generated by cp-install (pi-command-post); edits are refused on reinstall without --force.",
		'ExecStart="/opt/node/bin/node" "/home/u/.pi-command-post/app/src/service/daemon.ts" "run"',
		"WorkingDirectory=/home/u/.pi-command-post",
		'Environment="CP_HOME=/home/u/.pi-command-post"',
		'Environment="CP_MODE=multi"',
		'Environment="PATH=/opt/node/bin:/usr/bin"',
		"Type=simple", "Restart=on-failure", "RestartSec=5", "RestartSteps=5", "RestartMaxDelaySec=300",
		"RestartPreventExitStatus=78", "KillMode=process", "TimeoutStopSec=30",
		"StartLimitIntervalSec=1800", "StartLimitBurst=6", "WantedBy=default.target",
	]) assert.ok(text.split("\n").includes(line), `missing ${line}\n${text}`);
	assert.doesNotMatch(text, /CP_VIEWER|CP_PARENT_MODEL|sudo/);
	assert.equal(unitNode(text), "/opt/node/bin/node");
	assert.equal(DAEMON_UNIT, "cp-daemon.service");
});

test("daemon-backend's LEGACY_UNITS are units.ts's legacy unit names (the backend cannot import units.ts)", () => {
	assert.deepEqual([...LEGACY_UNITS], [PARENT_UNIT, VIEW_UNIT, HEALTH_UNIT, HEALTH_TIMER, UPDATE_UNIT, UPDATE_TIMER]);
});

test("cp-view.service: the viewer on the tailnet, always restarted", () => {
	const text = renderUnits(input)[VIEW_UNIT]!;
	assert.ok(text.includes('ExecStart="/opt/node/bin/node" "/home/u/.pi-command-post/app/src/viewer/cli.ts" "--home" "/home/u/.pi-command-post" "--require-tailnet" "--port" "8766"'), text);
	for (const line of ["Restart=always", "RestartSec=10", "StartLimitIntervalSec=0"]) assert.ok(text.split("\n").includes(line), line);
});

test("cp-health.service + cp-health.timer: a oneshot watchdog every 5 minutes, from 3 minutes after boot", () => {
	const units = renderUnits(input);
	const service = units[HEALTH_UNIT]!.split("\n");
	for (const line of ["Type=oneshot", "TimeoutStartSec=120", 'ExecStart="/opt/node/bin/node" "/home/u/.pi-command-post/app/src/service/health.ts"', 'Environment="CP_HOME=/home/u/.pi-command-post"', 'Environment="CP_VIEWER_PORT=8766"']) assert.ok(service.includes(line), line);
	assert.ok(!service.includes("[Install]"), "the service runs from its timer, never enabled itself");
	const timer = units[HEALTH_TIMER]!.split("\n");
	for (const line of ["OnBootSec=3min", "OnUnitActiveSec=5min", `Unit=${HEALTH_UNIT}`, "WantedBy=timers.target"]) assert.ok(timer.includes(line), line);
});

test("cp-update.service + cp-update.timer: a oneshot updater in its own unit every 5 minutes, from 10 minutes after boot", () => {
	const units = renderUnits(input);
	const service = units[UPDATE_UNIT]!.split("\n");
	for (const line of ["Type=oneshot", "TimeoutStartSec=45min", 'ExecStart="/opt/node/bin/node" "/home/u/.pi-command-post/app/src/service/update.ts"', 'Environment="CP_HOME=/home/u/.pi-command-post"', 'Environment="CP_MODE=multi"', 'Environment="CP_VIEWER_PORT=8766"']) assert.ok(service.includes(line), line);
	assert.ok(!service.includes("[Install]"), "the service runs from its timer, never enabled itself");
	const timer = units[UPDATE_TIMER]!.split("\n");
	for (const line of ["OnBootSec=10min", "OnUnitActiveSec=5min", `Unit=${UPDATE_UNIT}`, "WantedBy=timers.target"]) assert.ok(timer.includes(line), line);
});

test("cp-operator.service: the pinned text — forking tmux with the wrapper, killed by session name; rendered only with tmux", () => {
	assert.equal(renderUnits(input)[OPERATOR_UNIT], undefined, "no tmux, no unit");
	assert.equal(renderUnits({ ...input, tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" })[OPERATOR_UNIT], [
		"# Generated by cp-install (pi-command-post); edits are refused on reinstall without --force.",
		"[Unit]",
		"Description=pi-command-post operator session in tmux (never at boot; the dashboard's Start session)",
		"",
		"[Service]",
		"Type=forking",
		'ExecStart="/usr/bin/tmux" "new-session" "-d" "-s" "cp-operator" "/home/u/.local/bin/cp-operator"',
		'ExecStop="/usr/bin/tmux" "kill-session" "-t" "cp-operator"',
		"WorkingDirectory=/home/u/.pi-command-post",
		'Environment="CP_HOME=/home/u/.pi-command-post"',
		'Environment="CP_MODE=multi"',
		'Environment="PATH=/opt/node/bin:/usr/bin"',
		"",
		"[Install]",
		"WantedBy=default.target",
		"",
	].join("\n"));
});

test("cp-operator-resume.service: the same unit with the fixed `-c` on the wrapper; rendered only with tmux", () => {
	assert.equal(renderUnits(input)[OPERATOR_RESUME_UNIT], undefined, "no tmux, no unit");
	const units = renderUnits({ ...input, tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" });
	const resume = units[OPERATOR_RESUME_UNIT]!.split("\n");
	assert.ok(resume.includes('ExecStart="/usr/bin/tmux" "new-session" "-d" "-s" "cp-operator" "/home/u/.local/bin/cp-operator" "-c"'), resume.join("\n"));
	assert.deepEqual(resume.filter((line) => !line.startsWith("ExecStart=") && !line.startsWith("Description=")), units[OPERATOR_UNIT]!.split("\n").filter((line) => !line.startsWith("ExecStart=") && !line.startsWith("Description=")), "otherwise the same unit");
});

test("no unit carries sudo or a secret; only CP_*, PATH and the model name", () => {
	for (const text of Object.values(renderUnits({ ...input, parentModel: "m/x" }))) {
		assert.doesNotMatch(text, /sudo|KEY|TOKEN|SECRET|PASSWORD/i);
		for (const line of text.split("\n").filter((row) => row.startsWith("Environment="))) assert.match(line, /^Environment="(?:CP_[A-Z_]+|PATH)=/);
	}
});

test("systemd words escape quotes, backslashes, % specifiers and ExecStart $; a line break is refused", () => {
	const text = renderUnits({ ...input, app: '/tmp/a "b" 100%\\x $HOME' })[PARENT_UNIT]!;
	assert.ok(text.includes('ExecStart="/opt/node/bin/node" "/tmp/a \\"b\\" 100%%\\\\x $$HOME/src/service/supervise.ts"'), text);
	assert.ok(text.includes('Environment="CP_HOME=/home/u/.pi-command-post"'), text);
	assert.throws(() => renderUnits({ ...input, app: "/tmp/a\nExecStart=/bin/evil" }), /line break/);
	assert.throws(() => renderUnits({ ...input, port: 0 }), /port/);
});

test("PATH is stable across shells: two PATHs differing only in fnm_multishells render identical units; real differences still differ", () => {
	const node = "/home/u/.local/share/fnm/node-versions/v24.1.0/installation/bin/node";
	const shell = (id: string) => `/run/user/1000/fnm_multishells/${id}/bin:/home/u/.cargo/bin:/usr/bin:/usr/bin:/bin:`;
	const a = renderUnits({ ...input, node, path: shell("111_1"), tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" });
	const b = renderUnits({ ...input, node, path: shell("222_2"), tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" });
	assert.deepEqual(a, b);
	assert.ok(a[PARENT_UNIT]!.includes('Environment="PATH=/home/u/.local/share/fnm/node-versions/v24.1.0/installation/bin:/home/u/.cargo/bin:/usr/bin:/bin"'), a[PARENT_UNIT]);
	assert.notDeepEqual(renderUnits({ ...input, node, path: shell("111_1") }), renderUnits({ ...input, node, path: `${shell("111_1")}:/opt/gh/bin` }), "a real PATH dir still changes the unit");
	const ephemeral = "/run/user/1000/fnm_multishells/111_1/bin/node";
	assert.ok(renderUnits({ ...input, node: ephemeral, path: shell("222_2") })[PARENT_UNIT]!.includes('Environment="PATH=/run/user/1000/fnm_multishells/111_1/bin:/home/u/.cargo/bin:/usr/bin:/bin"'), "the ExecStart node's own dir is kept even under fnm_multishells");
});

test("WorkingDirectory= is a bare path (systemd refuses quotes there); % doubled; what it cannot carry is refused", () => {
	for (const [name, text] of Object.entries(renderUnits({ ...input, home: "/home/u/cp-100%", tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" }))) {
		if (!name.endsWith(".service")) continue; // a timer has no Working Directory=
		assert.ok(text.split("\n").includes("WorkingDirectory=/home/u/cp-100%%"), text);
	}
	for (const home of ["/home/u/my home", "/home/u/a\tb", '/home/u/"q"', "/home/u/it's", "/home/u/a\\b", "/home/u/a\x07b", "/home/u/a\nb"]) {
		assert.throws(() => renderUnits({ ...input, home }), /WorkingDirectory= cannot carry/, home);
	}
});

test("systemd-analyze --user verify accepts the rendered units (skipped without systemd-analyze)", (t) => {
	const dir = mkdtempSync(join(tmpdir(), "cp-units-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	const app = join(dir, "app");
	const home = join(dir, "home");
	const runtime = join(dir, "run");
	for (const sub of ["src/service", "src/viewer"]) mkdirSync(join(app, sub), { recursive: true });
	for (const script of ["src/service/supervise.ts", "src/service/health.ts", "src/service/update.ts", "src/service/daemon.ts", "src/viewer/cli.ts"]) writeFileSync(join(app, script), "");
	mkdirSync(home);
	mkdirSync(runtime, { mode: 0o700 });
	const rendered = { ...renderUnits({ ...input, node: process.execPath, app, home }), [DAEMON_UNIT]: renderDaemonUnit({ ...input, node: process.execPath, app, home }) };
	const files = Object.entries(rendered).map(([name, text]) => {
		writeFileSync(join(dir, name), text);
		return join(dir, name);
	});
	const result = spawnSync("systemd-analyze", ["--user", "verify", ...files], { encoding: "utf8", env: { ...process.env, XDG_RUNTIME_DIR: runtime } });
	if (result.error) return t.skip(`systemd-analyze unavailable: ${result.error.message}`);
	if (/Failed to initialize manager/.test(result.stderr)) return t.skip(`systemd-analyze cannot run here: ${result.stderr.trim()}`);
	assert.equal(result.status, 0, `${result.stdout}${result.stderr}`);
	assert.doesNotMatch(result.stderr, /WorkingDirectory|fatal|bad unit/i);
});

test("the cp-operator wrapper: CP_HOME, multi mode, the service viewer, from any directory", (t) => {
	const dir = mkdtempSync(join(tmpdir(), "cp-wrapper-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	const home = join(dir, "it's home");
	const app = join(dir, "app");
	mkdirSync(join(app, "bin"), { recursive: true });
	mkdirSync(home);
	writeFileSync(join(app, "bin/cp-operator"), '#!/bin/sh\nprintf "%s|%s|%s|%s|%s\\n" "$CP_HOME" "$CP_MODE" "$CP_OPERATOR_VIEWER" "$(pwd)" "$*"\n');
	chmodSync(join(app, "bin/cp-operator"), 0o755);
	const wrapper = join(dir, "cp-operator");
	writeFileSync(wrapper, renderOperatorWrapper({ app, home }));
	chmodSync(wrapper, 0o755);
	const out = execFileSync(wrapper, ["--model", "x y"], { cwd: tmpdir(), encoding: "utf8" }).trim();
	assert.equal(out, `${home}|multi|service|${home}|--model x y`);
});

test("viewerHost: CP_VIEWER_HOST in cp-parent/cp-view/cp-health/cp-update and the wrapper, never the operator units; absent, every file is unchanged", (t) => {
	const tmuxInput = { ...input, tmux: "/usr/bin/tmux", wrapper: "/home/u/.local/bin/cp-operator" };
	const plain = renderUnits(tmuxInput);
	const pinned = renderUnits({ ...tmuxInput, viewerHost: "100.70.1.2" });
	const line = 'Environment="CP_VIEWER_HOST=100.70.1.2"';
	for (const name of [PARENT_UNIT, VIEW_UNIT, HEALTH_UNIT, UPDATE_UNIT]) {
		assert.ok(pinned[name]!.split("\n").includes(line), `${name}\n${pinned[name]}`);
		assert.equal(pinned[name]!.split("\n").filter((row) => row !== line).join("\n"), plain[name], `${name}: only the one line differs`);
	}
	for (const name of [OPERATOR_UNIT, OPERATOR_RESUME_UNIT, HEALTH_TIMER, UPDATE_TIMER]) assert.equal(pinned[name], plain[name], name);
	for (const text of Object.values(plain)) assert.doesNotMatch(text, /CP_VIEWER_HOST/);
	assert.deepEqual(renderUnits({ ...tmuxInput, viewerHost: undefined }), plain);
	assert.equal(renderOperatorWrapper({ app: "/a", home: "/h", viewerHost: undefined }), renderOperatorWrapper({ app: "/a", home: "/h" }));
	assert.doesNotMatch(renderOperatorWrapper({ app: "/a", home: "/h" }), /CP_VIEWER_HOST/);

	assert.deepEqual(unitViewerHost(pinned[VIEW_UNIT]), { generated: true, host: "100.70.1.2" });
	assert.deepEqual(unitViewerHost(renderUnits({ ...input, viewerHost: "fd7a:115c:a1e0::1" })[VIEW_UNIT]), { generated: true, host: "fd7a:115c:a1e0::1" });
	assert.deepEqual(unitViewerHost(plain[VIEW_UNIT]), { generated: true });
	assert.deepEqual(unitViewerHost('[Service]\nEnvironment="CP_VIEWER_HOST=10.0.0.1"\n'), { generated: false, host: "10.0.0.1" }, "a hand-written unit");
	assert.deepEqual(unitViewerHost(undefined), { generated: false });

	const dir = mkdtempSync(join(tmpdir(), "cp-wrapper-host-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	mkdirSync(join(dir, "app/bin"), { recursive: true });
	writeFileSync(join(dir, "app/bin/cp-operator"), '#!/bin/sh\nprintf "%s\\n" "$CP_VIEWER_HOST"\n');
	chmodSync(join(dir, "app/bin/cp-operator"), 0o755);
	const wrapperText = renderOperatorWrapper({ app: join(dir, "app"), home: dir, viewerHost: "100.70.1.2" });
	assert.equal(wrapperViewerHost(wrapperText), "100.70.1.2");
	assert.equal(wrapperViewerHost(renderOperatorWrapper({ app: "/a", home: "/h" })), undefined);
	writeFileSync(join(dir, "cp-operator"), wrapperText);
	chmodSync(join(dir, "cp-operator"), 0o755);
	assert.equal(execFileSync(join(dir, "cp-operator"), { encoding: "utf8", env: { PATH: process.env.PATH ?? "" } }).trim(), "100.70.1.2");
});

test("models: the wrapper exports CP_PARENT_MODEL and CP_OPERATOR_MODEL when pinned, else is unchanged; unitParentModel/wrapperModels read them back", (t) => {
	const plain = renderOperatorWrapper({ app: "/a", home: "/h" });
	assert.ok(plain.split("\n").includes("export CP_HOME='/h' CP_MODE=multi CP_OPERATOR_VIEWER=service"), plain);
	assert.equal(renderOperatorWrapper({ app: "/a", home: "/h", parentModel: undefined, operatorModel: undefined }), plain);
	const pinned = renderOperatorWrapper({ app: "/a", home: "/h", viewerHost: "100.70.1.2", parentModel: "openai/gpt-6.1-sol", operatorModel: "anthropic/claude-opus-5-5" });
	assert.ok(pinned.split("\n").includes("export CP_HOME='/h' CP_MODE=multi CP_OPERATOR_VIEWER=service CP_VIEWER_HOST='100.70.1.2' CP_PARENT_MODEL='openai/gpt-6.1-sol' CP_OPERATOR_MODEL='anthropic/claude-opus-5-5'"), pinned);
	assert.equal(pinned.split("\n").filter((row) => !row.startsWith("export ")).join("\n"), plain.split("\n").filter((row) => !row.startsWith("export ")).join("\n"), "only the export line differs");
	assert.deepEqual(wrapperModels(pinned), { generated: true, parent: "openai/gpt-6.1-sol", operator: "anthropic/claude-opus-5-5" });
	assert.deepEqual(wrapperModels(plain), { generated: true });
	assert.deepEqual(wrapperModels(undefined), { generated: false });

	assert.deepEqual(unitParentModel(renderUnits({ ...input, parentModel: "openai/gpt-6.1-sol" })[PARENT_UNIT]), { generated: true, model: "openai/gpt-6.1-sol" });
	assert.deepEqual(unitParentModel(renderUnits({ ...input, parentModel: "p/a%b" })[PARENT_UNIT]), { generated: true, model: "p/a%b" }, "systemd escapes undone");
	assert.deepEqual(unitParentModel(renderUnits(input)[PARENT_UNIT]), { generated: true });
	assert.deepEqual(unitParentModel('[Service]\nEnvironment="CP_PARENT_MODEL=x/y"\n'), { generated: false, model: "x/y" }, "a hand-written unit");
	for (const text of Object.values(renderUnits({ ...input, parentModel: "openai/gpt-6.1-sol", operatorModel: "a/b" }))) assert.doesNotMatch(text, /CP_OPERATOR_MODEL/, "the operator model lives in the wrapper only");

	const dir = mkdtempSync(join(tmpdir(), "cp-wrapper-models-"));
	t.after(() => rmSync(dir, { recursive: true, force: true }));
	mkdirSync(join(dir, "app/bin"), { recursive: true });
	writeFileSync(join(dir, "app/bin/cp-operator"), '#!/bin/sh\nprintf "%s|%s\\n" "$CP_PARENT_MODEL" "$CP_OPERATOR_MODEL"\n');
	chmodSync(join(dir, "app/bin/cp-operator"), 0o755);
	writeFileSync(join(dir, "cp-operator"), renderOperatorWrapper({ app: join(dir, "app"), home: dir, parentModel: "p/m", operatorModel: "o/m" }));
	chmodSync(join(dir, "cp-operator"), 0o755);
	assert.equal(execFileSync(join(dir, "cp-operator"), { encoding: "utf8", env: { PATH: process.env.PATH ?? "" } }).trim(), "p/m|o/m");
});

test("install targets: the user's systemd dir and ~/.local/bin, XDG_CONFIG_HOME honoured", () => {
	assert.deepEqual(installTargets({ HOME: "/home/u" }), { unitDir: "/home/u/.config/systemd/user", binDir: "/home/u/.local/bin" });
	assert.equal(installTargets({ HOME: "/home/u", XDG_CONFIG_HOME: "/cfg" }).unitDir, "/cfg/systemd/user");
});
