/**
 * The optional sub2api gateway's admin key at rest (cp-er76): one 0600 `gateway.env` in a 0700
 * `${XDG_CONFIG_HOME:-~/.config}/pi-command-post/`, outside every home and every unit. cp-install
 * writes it (`src/service/gateway.ts`); the parent host loads it into a parent's env at spawn
 * (`parentEnv`, `src/cp-bridge.ts`) only for a home with `data/capacity.json`. The key is never
 * printed: every problem names the path and a reason, never content.
 */
import { readFileSync, statSync } from "node:fs";
import { join, resolve } from "node:path";
import { layoutForHome, type Mode } from "./contracts.ts";

const KEY_LINE = /^CP_GATEWAY_ADMIN_KEY=(.*)$/m;

export function gatewayKeyFile(env: NodeJS.ProcessEnv): string | undefined {
	const config = env.XDG_CONFIG_HOME || (env.HOME ? join(env.HOME, ".config") : undefined);
	return config ? resolve(config, "pi-command-post", "gateway.env") : undefined;
}

/** EnvironmentFile-compatible text: one comment, one `CP_GATEWAY_ADMIN_KEY=` line. */
export function renderGatewayKeyFile(key: string): string {
	return `# Generated by cp-install (pi-command-post): the sub2api admin key; loaded by the parent host, never printed.\nCP_GATEWAY_ADMIN_KEY=${key}\n`;
}

/** The first `CP_GATEWAY_ADMIN_KEY=` value in a key file's text. */
export function gatewayKeyFrom(text: string): string | undefined {
	return KEY_LINE.exec(text)?.[1]?.trim() || undefined;
}

/** Why `key` cannot be stored (never quoting it), or undefined when it can. */
export function validGatewayKey(key: string): string | undefined {
	if (key.length === 0) return "the key is empty";
	if (key.length > 4096) return "the key is longer than 4096 characters";
	if (!/^[\x21-\x7e]+$/.test(key) || /["'\\]/.test(key)) return "the key holds whitespace, a quote, a backslash or a non-printable character";
	return undefined;
}

/** The key in `file`; `problem` when it is not usable (group/other bits, no key line); neither when absent. */
export function readGatewayKey(file: string): { key?: string; problem?: string } {
	let mode: number;
	try {
		mode = statSync(file).mode & 0o777;
	} catch (error) {
		return (error as NodeJS.ErrnoException).code === "ENOENT" ? {} : { problem: `${file} is unreadable: ${(error as NodeJS.ErrnoException).code ?? "error"}` };
	}
	if ((mode & 0o077) !== 0) return { problem: `${file} is mode ${mode.toString(8)}, readable beyond its owner; chmod 600 ${file}` };
	let key: string | undefined;
	try {
		key = gatewayKeyFrom(readFileSync(file, "utf8"));
	} catch (error) {
		return { problem: `${file} is unreadable: ${(error as NodeJS.ErrnoException).code ?? "error"}` };
	}
	return key ? { key } : { problem: `${file} holds no CP_GATEWAY_ADMIN_KEY= line` };
}

/** The file's key for a parent of `home`: only when that home has `data/capacity.json`; a refused file is one stderr line (the host log). */
export function parentGatewayKey(home: string, mode: Mode, env: NodeJS.ProcessEnv): string | undefined {
	const file = gatewayKeyFile(env);
	if (!file) return undefined;
	try {
		statSync(join(home, layoutForHome(mode, home).data, "capacity.json"));
	} catch {
		return undefined; // no gateway configured for this home: quota stays off:no admin key
	}
	const { key, problem } = readGatewayKey(file);
	if (problem) process.stderr.write(`cp-bridge: gateway admin key not loaded: ${problem}\n`);
	return key;
}
