import type { ComponentChildren } from "preact";
import { useState } from "preact/hooks";
import type { MapResponse } from "../../src/viewer/api-types.ts";
import { amount, count, money, phaseText } from "../format.ts";
import { jobHref } from "../routes.ts";
import { ContextChip } from "../components/ContextChip.tsx";
import { JobsViews } from "../components/JobsViews.tsx";
import { PageHeader } from "../components/PageHeader.tsx";
import { expiry, MandateHistoryToggle, mapJobs, mapLanes, MapGraph, phaseClass, SourceWarnings } from "./MapGraph.tsx";
import { Icon } from "../components/icons.tsx";
const phases=["working","not dispatched","held","failed","launching","done"];
const relations=["blocked by · open","stranded","blocked by · satisfied","dependency removed","pipeline","waits on PR · CI red","superseded by","repairs"];
export function DependencyMap({data}:{data:MapResponse}) {
 const [legend,setLegend]=useState(false),[history,setHistory]=useState(false),[selection,setSelection]=useState<string|null>(null);
 const lanes=mapLanes(data,history);
 const visibleIds=new Set(lanes.flatMap(l=>[...(l.mandate ? [l.mandate.id] : []),...l.jobs.map(n=>n.id)]));
 const selected=selection && visibleIds.has(selection) ? selection : null;
 const job=data.nodes.find(n=>n.id===selected),mandate=data.items.find(m=>m.id===selected);
 const stranded=data.edges.filter(e=>e.kind==="stranded" && data.nodes.find(n=>n.id===e.to)?.ledger_status!=="closed");
 const relationText=(id:string)=>data.edges.filter(e=>e.from===id || e.to===id).map(e=>({kind:e.kind,text:e.from===id ? `Blocks ${e.to} · ${e.kind}` : `Blocked by ${e.from} · ${e.kind}`}));
 const prStatus=job?.pr_status==="merged" ? "merged" : job?.ci ? `CI ${job.ci}` : job?.pr_status;
 const pr=job?.pr_url ? <a class="map-pr" href={job.pr_url} title={job.pr_url}>#{job.pr_url.split("/").at(-1)}{prStatus ? ` · ${prStatus}` : ""}</a> : "-";
 const facts:[string,ComponentChildren][]=job ? [["covered by",job.mandate_id ?? "No mandate"],["ledger",job.ledger_status ?? "unknown"],["model",job.model ?? "-"],...(job.context ? [["context",<ContextChip usage={job.context}/>] as [string,ComponentChildren]] : []),["cost",money(job.cost_usd)],["PR",pr]] : mandate ? [["spend",`${money(mandate.spend?.usd ?? null)} / ${money(mandate.spend_cap.usd)}`],["token ceiling",`${amount(mandate.spend?.tokens ?? null)} / ${amount(mandate.spend_cap.tokens)}`],["jobs",`${count(mandate.spend?.jobs ?? null)} / ${count(mandate.job_cap)}`],["in flight",`${count(mandate.spend?.inFlight ?? null)} / ${count(mandate.dispatch_parallelism)}`],["asks you on",mandate.ask_on.join(" · ") || "-"]] : [];
 const mobileJob=(n:MapResponse["nodes"][number])=><a key={n.id} href={jobHref(n.id)} title={`${n.id}: ${n.title}`} aria-label={`${n.id}: ${n.title}`}><span class="map-stem" aria-hidden="true"/><span class="map-mobile-job"><span><i class={phaseClass(n.phase)}/><code>{n.id}</code><small>{phaseText(n.phase)}</small></span><span class="map-label">{n.title}</span>{relationText(n.id).map((r,i)=><span class={`map-relation-${r.kind}`} key={i}>{r.text}</span>)}{n.phase==="failed" && <span>ledger {n.ledger_status ?? "unknown"} · can continue on its lease</span>}</span></a>;
 return <div class="map-screen"><header class="map-heading"><PageHeader title="Jobs"/><div class="map-toolbar"><JobsViews current="map"/><div class="map-legend-summary">{["open","satisfied"].map(k=><span class={`map-legend-chip map-edge-${k}`} key={k}>← {k==="open" ? "blocked by · open" : "satisfied"}</span>)}<button class="map-legend-button" aria-label="Show full legend" aria-pressed={legend} onClick={()=>setLegend(!legend)}>?</button></div><MandateHistoryToggle data={data} checked={history} onChange={setHistory}/></div></header><SourceWarnings data={data}/>
  {legend && <div class="map-full-legend">{phases.map(p=><span key={p}><i class={phaseClass(p)}/>{p}</span>)}{relations.map((r,i)=><span key={r} class={i===1 ? "map-stranded-text" : i===5 ? "map-red-text" : ""}>{i===0 || i===2 ? "← " : "⇢ "}{r}</span>)}</div>}
  {data.stranded_count===null ? <p class="map-status">Dependency status unavailable.</p> : stranded.length ? <section class="map-stranded" aria-label="Stranded dependencies"><h2>{stranded.length} stranded {stranded.length===1 ? "dependency" : "dependencies"}</h2>{stranded.map(e=><p key={`${e.from}:${e.to}`}>{e.to} is blocked by {e.from}, under {data.nodes.find(n=>n.id===e.from)?.mandate_id ?? "no mandate"} ({data.items.find(m=>m.id===data.nodes.find(n=>n.id===e.from)?.mandate_id)?.status ?? "uncovered or missing"}).</p>)}</section> : <p class="map-status" title="No open blocker sits under a paused, expired or revoked mandate, or under none."><span class="map-check" aria-hidden="true">✓</span>No stranded dependencies</p>}
  {!data.nodes.length && data.availability.ledger!=="unavailable" && data.availability.fleet!=="unavailable" && <p class="mandates-empty">No jobs recorded.</p>}
  <div class="map-phone map-mobile-lanes">{lanes.map((lane,i)=>{const {shown,hidden}=mapJobs(lane.jobs);return <section key={`${lane.project}:${lane.mandate?.id ?? "none"}`}>
   {(i===0 || lanes[i-1]?.project!==lane.project) && <h2>{lane.project}</h2>}
   <div class={`map-lane-head ${lane.mandate && lane.mandate.status!=="active" ? "map-inactive" : ""}`}><div><code>{lane.mandate?.id ?? "No mandate"}</code><span>{lane.mandate ? expiry(lane.mandate,data.generated_at) : ""}</span></div>{lane.mandate && <><p title={lane.mandate.objective}>{lane.mandate.objective}</p><small>{money(lane.mandate.spend?.usd ?? null)} / {money(lane.mandate.spend_cap.usd)} &middot; {amount(lane.mandate.spend?.tokens ?? null)} / {amount(lane.mandate.spend_cap.tokens)} tok &middot; asks on {lane.mandate.ask_on.join(", ") || "-"}</small></>}</div>
   <div class="map-lane-jobs">{shown.map(mobileJob)}{!!hidden.length && <details class="map-done-details"><summary>+{hidden.length} more done</summary>{hidden.map(mobileJob)}</details>}</div>
  </section>;})}</div>
  <div class="map-desktop map-workspace"><MapGraph data={data} lanes={lanes} selection={selected} onSelect={id=>setSelection(selected===id ? null : id)} healthy={data.stranded_count!==null && !stranded.length}/><aside class={`map-selection${!job && !mandate ? " map-selection-empty" : ""}`} aria-label="Selection">{job || mandate ? <><header><code>{job ? "job" : "mandate"} · {selected}</code><button aria-label="Clear selection" onClick={()=>setSelection(null)}>×</button></header><h2 title={job?.title ?? mandate?.objective}>{job?.title ?? mandate?.objective}</h2><div><span class="mandate-chip">{job ? phaseText(job.phase) : mandate?.status}</span></div><dl>{facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div class="map-selection-relations"><h3>{job ? "Relations" : "Jobs it covers"}</h3>{job ? relationText(job.id).length ? relationText(job.id).map((r,i)=><p key={i} class={`map-relation-${r.kind}`}>{r.text}</p>) : <p>No dependencies.</p> : data.nodes.filter(n=>n.mandate_id===mandate?.id).map(n=><p key={n.id}>{n.id} · {phaseText(n.phase)}</p>)}</div>{job && <a href={jobHref(job.id)}>Open job →</a>}</> : <><Icon name="map" size={28}/><h2>Select a job or mandate</h2><p>Its details, blockers and what it blocks show here.<br/>Nothing is dimmed until you pick one.</p></>}</aside></div>
 </div>;
}
