import type { JobResponse } from "../../src/viewer/api-types.ts";
import { elapsed, money, time } from "../format.ts";
import { CopyReply } from "../components/CopyReply.tsx";
import { ContextChip } from "../components/ContextChip.tsx";
import { PhaseDot, reviewText, CiSignal } from "./Jobs.tsx";
import "./job-detail.css";
export function JobDetail({data}:{data:JobResponse}) {
 const job=data.job;
 return <div class="job-detail"><div class="job-detail-main"><header class="job-detail-heading"><div class="job-badges"><span class={`job-badge job-badge-${job.phase}`}><PhaseDot phase={job.phase}/>{job.phase}</span><CiSignal job={job} badge/><span class="job-badge job-badge-review">{reviewText(job)}</span></div><h1>{job.title ?? job.id}</h1>{job.phase==="held" && <p>held = waiting on CI or review, normal for hours</p>}</header>
 {data.questions.map(q=><section class="job-question" key={q.id}><h2>{q.kind==="final_fix" ? "Final-fix approval open" : "Parent question open"}</h2><p><code>{q.id}</code> · {q.question}</p><p>Being handled by the operator session.</p></section>)}
 {data.asks.map(ask=><section class="job-question job-question-awaiting" key={ask.id}><h2>Awaiting you</h2><p>{ask.question}</p>{ask.options.map(option=><CopyReply key={option.label} reply={option.reply}/>)}</section>)}
 {job.summary && <p class="job-summary">{job.summary}</p>}{job.failure && <p class="job-failure">{job.failure}</p>}</div>
 <div class="job-detail-side"><dl class="job-facts"><div><dt>Wall clock</dt><dd>{elapsed(job.elapsed_seconds)} / {elapsed(job.limit_seconds)}</dd></div><div><dt>Head</dt><dd><code>{job.head?.slice(0,7) ?? "-"}</code></dd></div><div><dt>Model</dt><dd><code>{job.script_path ?? job.model ?? "-"}</code></dd></div><div><dt>Cost</dt><dd>{money(job.cost_usd)}</dd></div>{job.context && <div class="job-fact-wide"><dt>Context</dt><dd><ContextChip usage={job.context}/></dd></div>}<div class="job-fact-wide"><dt>Routing</dt><dd>{job.routing ?? "Not recorded"}</dd></div><div><dt>Mandate</dt><dd>{job.mandate_id ? <a href="#map"><code>{job.mandate_id}</code></a> : "Not recorded"}</dd></div><div><dt>PR</dt><dd>{job.pr_url ? <a href={job.pr_url}>#{job.pr_url.split("/").at(-1)} {job.pr_status ?? ""} ↗</a> : "Not recorded"}</dd></div><div class="job-fact-wide job-fact-desktop"><dt>CI</dt><dd><CiSignal job={job}/></dd></div><div class="job-fact-wide job-fact-desktop"><dt>Review</dt><dd>{reviewText(job)}</dd></div></dl>
 <div class="job-links">{data.artifact_href ? <a href={data.artifact_href}>Artifact · {data.artifact_name}</a> : data.files_href ? <a href={data.files_href}>Files</a> : <span>Files unavailable</span>}{data.run_href ? <a href={data.run_href}>Run log · events.jsonl</a> : <span>Run log unavailable</span>}</div></div>
 <section class="job-timeline"><h2>Timeline</h2>{data.timeline_truncated && <p class="job-meta">Recent recorded events shown</p>}{data.timeline.map((event,index)=><div class={`job-event job-event-${event.tone}`} key={`${event.at}-${index}`}><code>{time(event.at)}</code><span class="job-event-stem" aria-hidden="true"><span/></span><div><span>{event.label}</span><p>{event.meta}</p></div></div>)}{!data.timeline.length && <p class="jobs-empty">No recorded events.</p>}{job.phase!=="done" && <div class="job-event job-event-pending"><code>-</code><span class="job-event-stem" aria-hidden="true"><span/></span><div><span>Merge</span><p>not yet</p></div></div>}</section>
 </div>;
}
